# Development environment overrides
version: '3.8'

services:
  lms-backend:
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    command: ["python", "main.py"]

  ai-service:
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./backend:/app

  auth-service:
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./backend:/app

  celery-worker:
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./backend:/app

  # Development database with persistent data
  mongodb:
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro

  # Development Redis with persistent data
  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf

  # Development Kafka with persistent data
  kafka:
    ports:
      - "9092:9092"
    volumes:
      - kafka_dev_data:/var/lib/kafka/data

  # Development Elasticsearch with persistent data
  elasticsearch:
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_dev_data:/usr/share/elasticsearch/data

  # Disable monitoring in development (optional)
  # prometheus:
  #   profiles:
  #     - monitoring

  # grafana:
  #   profiles:
  #     - monitoring

volumes:
  mongodb_dev_data:
  redis_dev_data:
  kafka_dev_data:
  elasticsearch_dev_data: